version: '3.7'

networks:
  catalog:

services:
  postgres: 
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: catalog
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - catalog
    ports: 
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: catalog
      DB_PORT: 5432
    depends_on:
      - postgres
    command: yarn dev
    ports: 
      - "3000:3000"
    networks:
      - catalog